// Lista de medicamentos comuns para cadastro rápido
// Esta é uma base inicial que pode ser expandida no futuro.

export const COMMON_MEDICATIONS = [
    // Analgésicos e Antitérmicos
    { name: 'Dipirona', dosage: '500mg' },
    { name: 'Paracetamol', dosage: '750mg' },
    { name: 'Ibuprofeno', dosage: '400mg' },
    { name: 'Dorflex', dosage: '1 comprimido' },
    { name: 'Neosaldina', dosage: '1 drágea' },

    // Antialérgicos
    { name: 'Loratadina', dosage: '10mg' },
    { name: 'Allegra', dosage: '120mg' },

    // Para Estômago e Náuseas
    { name: 'Dramin', dosage: '50mg' },
    { name: 'Buscopan', dosage: '10mg' },
    { name: 'Estomazil', dosage: '1 envelope' },

    // Lista expandida
    { name: 'Acetato de Medroxiprogesterona', dosage: 'S.I 150 mg/ml trimestral' },
    { name: 'Acetil Acetilsalicilico', dosage: 'Comprimido 100 mg' },
    { name: 'Aciclovir', dosage: 'Comprimido 200 mg' },
    { name: 'Ácido Acetilsalicílico', dosage: 'Comprimido 500 mg' },
    { name: 'Ácido Fólico', dosage: 'Comprimido 5 mg' },
    { name: 'Ácido Fólico', dosage: 'Solução oral 0,2 mg/ml' },
    { name: 'Ácido Tranexâmico', dosage: 'Solução injetável 250 mg/5 ml' },
    { name: 'Água Destilada', dosage: 'Injetável, ampola 10 ml' },
    { name: 'Albendazol', dosage: 'Comprimido mastigável 400 mg' },
    { name: 'Albendazol', dosage: 'Solução oral 40 mg/ml' },
    { name: 'Alendronato de Sódio', dosage: 'Comprimido 70 mg' },
    { name: 'Aminofilina', dosage: 'Comprimido 100 mg' },
    { name: 'Amiodarona', dosage: 'Comprimido 200 mg' },
    { name: 'Amoxicilina', dosage: 'Pó para suspensão oral 50 mg/ml' },
    { name: 'Amoxicilina', dosage: 'Cápsula 500 mg' },
    { name: 'Amoxicilina + Clavulanato de Potássio', dosage: 'Suspensão oral 50 mg/12,5 mg por ml' },
    { name: 'Amoxicilina + Clavulanato de Potássio', dosage: 'Comprimido 500 mg/125 mg' },
    { name: 'Atenolol', dosage: 'Comprimido 50 mg' },
    { name: 'Atenolol', dosage: 'Comprimido 100 mg' },
    { name: 'Azitromicina', dosage: 'Suspensão oral 40 mg/ml' },
    { name: 'Azitromicina', dosage: 'Comprimido 500 mg' },
    { name: 'Beclometasona', dosage: 'Aerossol oral 250 mcg (200 doses)' },
    { name: 'Cl. de Benzalcônio 0,1 mg/ml + Cl. de Na 9 mg/ml', dosage: 'Solução nasal, frasco 30 ml' },
    { name: 'Benzilpenicilina Procaína + Potássica', dosage: 'Suspensão injetável 300.000 UI + 100.000 UI' },
    { name: 'Benzilpenicilina Benzatina', dosage: 'Pó para suspensão injetável 1.200.000 UI' },
    { name: 'Benzilpenicilina Benzatina', dosage: 'Pó para suspensão injetável 600.000 UI' },
    { name: 'Benzilpenicilina Potássica', dosage: 'Pó para suspensão injetável 5.000.000 UI' },
    { name: 'Benzoilestradiol', dosage: 'Gel vaginal 10%' },
    { name: 'Besilato de Anlodipino', dosage: 'Comprimido 5 mg' },
    { name: 'Besilato de Anlodipino', dosage: 'Comprimido 10 mg' },
    { name: 'Biperideno Lactato', dosage: 'Solução injetável 5 mg/ml' },
    { name: 'Brometo de Ipratrópio (Atrovent)', dosage: 'Solução para inalação 0,25 mg/ml' },
    { name: 'Bromidrato de Fenoterol (Berotec)', dosage: 'Solução inalatória, frasco 20 ml' },
    { name: 'Butilbrometo de Escopolamina + Dipirona', dosage: 'Solução oral, frasco 20 ml' },
    { name: 'Captopril', dosage: 'Comprimido 25 mg' },
    { name: 'Carbamazepina', dosage: 'Comprimido 200 mg' },
    { name: 'Carbamazepina', dosage: 'Xarope 20 mg/ml' },
    { name: 'Carbocisteína', dosage: 'Xarope 50 mg/ml' },
    { name: 'Carbonato de Lítio', dosage: 'Comprimido 300 mg' },
    { name: 'Carvedilol', dosage: 'Comprimido 12,5 mg' },
    { name: 'Carvedilol', dosage: 'Comprimido 3,125 mg' },
    { name: 'Cetoconazol', dosage: 'Xampu 2%' },
    { name: 'Cetoprofeno', dosage: 'Solução injetável 50 mg/ml (pó liofilizado)' },
    { name: 'Clonazepam', dosage: 'Comprimido 2 mg' },
    { name: 'Clonazepam', dosage: 'Suspensão oral 2,5 mg/ml' },
    { name: 'Cloreto de Sódio', dosage: 'Solução nasal 0,9%' },
    { name: 'Cloridrato de Ambroxol', dosage: 'Xarope 15 mg/5 ml' },
    { name: 'Cloridrato de Amitriptilina', dosage: 'Comprimido 25 mg' },
    { name: 'Cloridrato de Biperideno', dosage: 'Comprimido 2 mg' },
    { name: 'Cloridrato de Cefalexina', dosage: 'Suspensão oral 50 mg/ml' },
    { name: 'Cloridrato de Cefalexina', dosage: 'Cápsula 500 mg' },
    { name: 'Cloridrato de Ciprofloxacino', dosage: 'Comprimido 500 mg' },
    { name: 'Cloridrato de Clomipramina', dosage: 'Comprimido 25 mg' },
    { name: 'Cloridrato de Clorpromazina', dosage: 'Comprimido 25 mg' },
    { name: 'Cloridrato de Clorpromazina', dosage: 'Comprimido 100 mg' },
    { name: 'Cloridrato de Clorpromazina', dosage: 'Solução oral 40 mg/ml' },
    { name: 'Cloridrato de Fluoxetina', dosage: 'Cápsula 20 mg' },
    { name: 'Cloridrato de Lidocaína', dosage: 'Gel 2%, bisnaga 30 g' },
    { name: 'Cloridrato de Lidocaína', dosage: 'Solução injetável 1%' },
    { name: 'Cloridrato de Metformina', dosage: 'Comprimido 500 mg' },
    { name: 'Cloridrato de Metformina', dosage: 'Comprimido 850 mg' },
    { name: 'Cloridrato de Metoclopramida', dosage: 'Comprimido 10 mg' },
    { name: 'Cloridrato de Nortriptilina', dosage: 'Cápsula 50 mg' },
    { name: 'Cloridrato de Propranolol', dosage: 'Comprimido 10 mg' },
    { name: 'Cloridrato de Propranolol', dosage: 'Comprimido 40 mg' },
    { name: 'Cloridrato de Ranitidina', dosage: 'Comprimido 150 mg' },
    { name: 'Cloridrato de Verapamil', dosage: 'Comprimido 80 mg' },
    { name: 'Cloridrato de Verapamil', dosage: 'Comprimido 120 mg' },
    { name: 'Clorpromazina', dosage: 'Solução injetável 5 mg/ml' },
    { name: 'Decanoato de Haloperidol', dosage: 'Solução injetável 50 mg/ml' },
    { name: 'Dexametasona', dosage: 'Creme 0,1%' },
    { name: 'Diazepam', dosage: 'Comprimido 5 mg' },
    { name: 'Diazepam', dosage: 'Comprimido 10 mg' },
    { name: 'Diazepam', dosage: 'Solução injetável 10 mg/2 ml' },
    { name: 'Diclofenaco Sódico', dosage: 'Comprimido 50 mg' },
    { name: 'Diclofenaco Sódico', dosage: 'Solução injetável 25 mg/ml' },
    { name: 'Digoxina', dosage: 'Comprimido 0,25 mg' },
    { name: 'Dinidrato de Isossorbida', dosage: 'Comprimido sublingual 5 mg' },
    { name: 'Dipirona', dosage: 'Solução injetável 500 mg/ml' },
    { name: 'Dipirona Sódica', dosage: 'Solução oral 500 mg/ml' },
    { name: 'Dipirona Sódica', dosage: 'Comprimido 500 mg' },
    { name: 'Dirpropionato de Beclometasona', dosage: 'Pó/solução inalatória 50 mcg/dose' },
    { name: 'Enantato de Noretisterona + Valerato de Estradiol', dosage: 'Injetável mensal 50 mg + 5 mg' },
    { name: 'Espironolactona', dosage: 'Comprimido 25 mg' },
    { name: 'Espironolactona', dosage: 'Comprimido 100 mg' },
    { name: 'Estearato de Eritromicina', dosage: 'Suspensão oral 50 mg/ml' },
    { name: 'Estearato de Eritromicina', dosage: 'Comprimido 500 mg' },
    { name: 'Estrogênio Conjugado', dosage: 'Bisnaga' },
    { name: 'Etinilestradiol + Levonorgestrel', dosage: 'Comprimido 0,03 mg + 0,15 mg (pílula mensal)' },
    { name: 'Fenitoína', dosage: 'Solução injetável 50 mg/ml (5 ml)' },
    { name: 'Fenitoína Sódica', dosage: 'Comprimido 100 mg' },
    { name: 'Fenobarbital', dosage: 'Comprimido 100 mg' },
    { name: 'Fenobarbital', dosage: 'Solução oral 40 mg/ml' },
    { name: 'Fenobarbital', dosage: 'Solução injetável 100 mg/ml (2 ml)' },
    { name: 'Fitomenadiona (Vitamina K)', dosage: 'Solução injetável 10 mg/ml' },
    { name: 'Fosfato Dissódico de Dexametasona', dosage: 'Solução injetável 4 mg/ml' },
    { name: 'Fosfato Sódico de Prednisolona', dosage: 'Solução oral 1,34 mg/ml' },
    { name: 'Furosemida', dosage: 'Comprimido 40 mg' },
    { name: 'Furosemida', dosage: 'Solução injetável 10 mg/ml' },
    { name: 'Glibenclamida', dosage: 'Comprimido 5 mg' },
    { name: 'Gliclazida', dosage: 'Comprimido 80 mg' },
    { name: 'Gliclazida', dosage: 'Comprimido 30 mg (liberação modificada)' },
    { name: 'Haloperidol', dosage: 'Comprimido 1 mg' },
    { name: 'Haloperidol', dosage: 'Comprimido 5 mg' },
    { name: 'Haloperidol', dosage: 'Solução oral 2 mg/ml' },
    { name: 'Haloperidol', dosage: 'Solução injetável 5 mg/ml' },
    { name: 'Hidróxido de Alumínio + Hidróxido de Magnésio', dosage: 'Comprimido dispersível 200 mg + 200 mg' },
    { name: 'Hidróxido de Alumínio + Hidróxido de Magnésio', dosage: 'Suspensão oral 35,6 mg + 37 mg por ml' },
    { name: 'Hidroclorotiazida', dosage: 'Comprimido 25 mg' },
    { name: 'Ibuprofeno', dosage: 'Comprimido 200 mg' },
    { name: 'Ibuprofeno', dosage: 'Comprimido 600 mg' },
    { name: 'Ibuprofeno', dosage: 'Suspensão oral 20 mg/ml' },
    { name: 'Ivermectina', dosage: 'Comprimido 6 mg' },
    { name: 'Levomepromazina', dosage: 'Comprimido 25 mg' },
    { name: 'Levomepromazina', dosage: 'Comprimido 100 mg' },
    { name: 'Levonorgestrel', dosage: 'Comprimido 1,5 mg (emergência)' },
    { name: 'Levotiroxina Sódica', dosage: 'Comprimido 25 mcg' },
    { name: 'Levotiroxina Sódica', dosage: 'Comprimido 50 mcg' },
    { name: 'Levotiroxina Sódica', dosage: 'Comprimido 100 mcg' },
    { name: 'Loratadina', dosage: 'Xarope 1 mg/ml' },
    { name: 'Loratadina', dosage: 'Comprimido 10 mg' },
    { name: 'Losartana Potássica', dosage: 'Comprimido 50 mg' },
    { name: 'Losartana Potássica', dosage: 'Comprimido 25 mg' },
    { name: 'Maleato de Dexclorfeniramina', dosage: 'Comprimido 2 mg' },
    { name: 'Maleato de Dexclorfeniramina', dosage: 'Solução oral 0,4 mg/ml' },
    { name: 'Maleato de Enalapril', dosage: 'Comprimido 5 mg' },
    { name: 'Maleato de Enalapril', dosage: 'Comprimido 20 mg' },
    { name: 'Mebendazol', dosage: 'Comprimido 100 mg' },
    { name: 'Mebendazol', dosage: 'Suspensão oral 20 mg/ml' },
    { name: 'Metildopa', dosage: 'Comprimido 250 mg' },
    { name: 'Metildopa', dosage: 'Comprimido 500 mg' },
    { name: 'Metoclopramida', dosage: 'Solução oral 4 mg/ml' },
    { name: 'Metronidazol', dosage: 'Suspensão oral 40 mg/ml' },
    { name: 'Metronidazol', dosage: 'Creme vaginal 5%' },
    { name: 'Metronidazol', dosage: 'Comprimido 250 mg' },
    { name: 'Miconazol (Nitrato)', dosage: 'Creme 2%' },
    { name: 'Midazolam', dosage: 'Solução injetável 1 mg/ml' },
    { name: 'Mononitrato de Isossorbida', dosage: 'Comprimido 40 mg' },
    { name: 'Neomicina + Bacitracina', dosage: 'Pomada 5 mg/g + 250 UI/g (bisnaga 10 g)' },
    { name: 'Nifedipino', dosage: 'Comprimido ou cápsula 10 mg' },
    { name: 'Nimesulida', dosage: 'Comprimido 100 mg' },
    { name: 'Nistatina', dosage: 'Suspensão oral 100.000 UI/ml' },
    { name: 'Nitrato de Miconazol', dosage: 'Creme vaginal 2%' },
    { name: 'Noretisterona', dosage: 'Comprimido 0,35 mg (amamentação)' },
    { name: 'Óleo Mineral', dosage: 'Frasco 50 ml' },
    { name: 'Omeprazol', dosage: 'Comprimido 20 mg' },
    { name: 'Paracetamol', dosage: 'Solução oral 200 mg/ml' },
    { name: 'Paracetamol', dosage: 'Comprimido 500 mg' },
    { name: 'Permetrina', dosage: 'Creme 5%' },
    { name: 'Permetrina', dosage: 'Loção 1%' },
    { name: 'Polivitamínico', dosage: 'Comprimido' },
    { name: 'Polivitamínico', dosage: 'Solução oral 200 mg/ml (frasco 20 ml)' },
    { name: 'Prednisona', dosage: 'Comprimido 5 mg' },
    { name: 'Prednisona', dosage: 'Comprimido 20 mg' },
    { name: 'Prometazina', dosage: 'Solução injetável 25 mg/ml' },
    { name: 'Prometazina', dosage: 'Comprimido 25 mg' },
    { name: 'Sais para Reidratação Oral', dosage: 'Pó para solução oral' },
    { name: 'Salbutamol', dosage: 'Aerossol 100 mcg/dose' },
    { name: 'Sinvastatina', dosage: 'Comprimido 10 mg' },
    { name: 'Sinvastatina', dosage: 'Comprimido 40 mg' },
    { name: 'Solução oleosa (ácido caprílico/cáprico/caprônico/linoleico/AGE/láurico)', dosage: 'Frasco 100 ml' },
    { name: 'Sulfametoxazol + Trimetoprima', dosage: 'Suspensão oral 40 mg + 8 mg/ml' },
    { name: 'Sulfametoxazol + Trimetoprima', dosage: 'Comprimido 400 mg + 80 mg' },
    { name: 'Sulfato Ferroso', dosage: 'Xarope 25 mg/ml' },
    { name: 'Sulfato Ferroso', dosage: 'Comprimido 40 mg (Fe++)' },
    { name: 'Tiabendazol', dosage: 'Suspensão oral 50 mg/ml' },
    { name: 'Tiabendazol', dosage: 'Comprimido 500 mg' },
    { name: 'Timolol', dosage: 'Solução oftálmica 0,25%' },
    { name: 'Timolol', dosage: 'Solução oftálmica 0,5%' },
    { name: 'Valproato de Sódio', dosage: 'Comprimido 250 mg' },
    { name: 'Valproato de Sódio', dosage: 'Comprimido 500 mg' },
    { name: 'Valproato de Sódio', dosage: 'Solução oral 57,624 mg/ml' },
    { name: 'Varfarina', dosage: 'Comprimido 5 mg' },
];
