# ios/Podfile
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

platform :ios, '13.4'
inhibit_all_warnings!
use_frameworks! :linkage => :static

target 'MedControlApp' do
  use_expo_modules!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # :hermes_enabled => false
  )

  # Adicione qualquer outra dependência de Pod aqui

  post_install do |installer|
    react_native_post_install(installer)

    # ---> INÍCIO DA CORREÇÃO PARA O FIREBASE <---
    # Este bloco corrige o problema de "does not define modules"
    installer.pods_project.targets.each do |target|
      if ['FirebaseCoreInternal', 'GoogleUtilities', 'FirebaseStorage', 'FirebaseAppCheckInterop', 'FirebaseAuthInterop', 'FirebaseCore', 'FirebaseCoreExtension'].include?(target.name)
        target.build_configurations.each do |config|
          config.build_settings['DEFINES_MODULE'] = 'YES'
        end
      end
    end
    # ---> FIM DA CORREÇÃO PARA O FIREBASE <---

    # Workaround para erro de "duplicate symbols"
    installer.pods_project.targets.each do |target|
      if target.name == 'React-Core'
        target.build_configurations.each do |config|
          config.build_settings['OTHER_LDFLAGS'] = '-ld_classic'
        end
      end
    end
  end
end