require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

$iOSVersion = '14.0'
platform :ios, $iOSVersion

target 'MedControlApp' do
  use_modular_headers!
  config = use_native_modules!
  use_frameworks! :linkage => :static

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true
  )

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
end

post_install do |installer|
  react_native_post_install(installer)

  # ===== A CORREÇÃO MÁGICA COMEÇA AQUI =====
  installer.pods_project.targets.each do |target|
    if target.name.start_with?('RNFB')
      target.build_configurations.each do |config|
        config.build_settings['HEADER_SEARCH_PATHS'] ||= '$(inherited)'
        # Adiciona o caminho para os cabeçalhos do Firebase Core
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Firebase/Core/Sources"'
      end
    end
    # Garante a versão do iOS em todos os targets
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $iOSVersion
    end
  end
  # ===== A CORREÇÃO MÁGICA TERMINA AQUI =====

end